# Generated by Django 3.2 on 2022-10-08 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Physiotherapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_physiotherapist', models.CharField(max_length=64)),
                ('surname_of_physiotherapist', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=64)),
                ('physiotherapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Physiotherapist_project.physiotherapist')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_session', models.CharField(max_length=64)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Physiotherapist_project.product')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Physiotherapist_project.session')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('physiotherapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Physiotherapist_project.physiotherapist')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Physiotherapist_project.price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Physiotherapist_project.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Physiotherapist_project.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('physiotherapist', 'date')},
            },
        ),
    ]
