# Generated by Django 3.2 on 2022-10-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Physiotherapist_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physiotherapist',
            name='surname_of_physiotherapist',
        ),
    ]
